applications/tidr/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  get "up" => "rails/health#show", as: :rails_health_check

  get "/auth/calendly", to: "calendly#connect"
  get "/auth/calendly/callback", to: "calendly#callback"
  post "/calendly/disconnect", to: "users#disconnect_calendly"

  get "/oauth/dropbox/callback", to: "oauth#dropbox"
  post "/dropbox/disconnect", to: "users#disconnect_dropbox"

  get "/zoom/connect", to: "zoom#connect"
  get "/zoom/callback", to: "zoom#callback"
  post "/zoom/disconnect", to: "users#disconnect_zoom"
  post "webhooks/zoom" => "webhooks#zoom"

  root "users#index"
end

applications/tidr/app/models/user.rb
require "net/http"

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :calendly_access_token, presence: true, if: -> { calendly_refresh_token.present? }
  validates :calendly_refresh_token, presence: true, if: -> { calendly_access_token.present? }
  validates :calendly_expires_at, presence: true, if: -> { calendly_access_token.present? }
  validates :dropbox_access_token, presence: true, if: -> { dropbox_refresh_token.present? }
  validates :dropbox_refresh_token, presence: true, if: -> { dropbox_access_token.present? }
  validates :dropbox_token_expires_at, presence: true, if: -> { dropbox_access_token.present? }
  validates :zoom_access_token, presence: true, if: -> { zoom_refresh_token.present? }
  validates :zoom_refresh_token, presence: true, if: -> { zoom_access_token.present? }
  validates :zoom_token_expires_at, presence: true, if: -> { zoom_access_token.present? }
end

applications/tidr/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @dropbox_connected = current_user.dropbox_access_token.present?
    @zoom_connected = current_user.zoom_access_token.present?
    if @zoom_connected
      from_param = params[:from].is_a?(String) ? params[:from] : nil
      to_param = params[:to].is_a?(String) ? params[:to] : nil

      from_date = from_param ? Date.parse(from_param).strftime("%Y-%m-%d") : (Time.now.utc - 1.year).strftime("%Y-%m-%d")
      to_date = to_param ? Date.parse(to_param).strftime("%Y-%m-%d") : Time.now.utc.strftime("%Y-%m-%d")

      @zoom_recordings = ZoomApi.fetch_recordings(current_user, from: from_date, to: to_date)
    else
      @zoom_recordings = []
    end

    CalendlyApi.refresh_token(current_user) if current_user.calendly_access_token.present?
    @calendly_connected = current_user.calendly_access_token.present?
    if @calendly_connected
      @meetings = CalendlyApi.fetch_upcoming_events(current_user)
    else
      @meetings = []
    end
  end

  def disconnect_calendly
    current_user.update(
      calendly_access_token: nil,
      calendly_expires_at: nil,
      calendly_refresh_token: nil,
      calendly_token_expires_at: nil,
      calendly_user_email: nil,
      calendly_user_name: nil,
      calendly_user_uri: nil,
    )

    redirect_to users_path, notice: "Successfully disconnected from Calendly."
  end

  def disconnect_dropbox
    current_user.update(
      dropbox_access_token: nil,
      dropbox_token_expires_at: nil,
      dropbox_refresh_token: nil,
      dropbox_email: nil,
    )

    redirect_to users_path, notice: "Successfully disconnected from Dropbox."
  end

  def disconnect_zoom
    current_user.update(
      zoom_access_token: nil,
      zoom_email: nil,
      zoom_host_id: nil,
      zoom_refresh_token: nil,
      zoom_user_id: nil,
    )

    redirect_to users_path, notice: "Successfully disconnected from Zoom."
  end
end

applications/tidr/app/helpers/users_helper.rb
module UsersHelper
end

applications/tidr/app/views/users/index.html.erb
<main>
  <h1>Dashboard</h1>

  <section class="dropbox">
    <h2>Dropbox</h2>
    <% if @dropbox_connected %>
      <p>You are connected to Dropbox as
        <strong><%= current_user.dropbox_email || "Unknown User" %></strong></p>
      <form method="post" action="<%= dropbox_disconnect_path %>">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <button type="submit" class="button button-dismiss disconnect">Disconnect Dropbox</button>
      </form>
    <% else %>
      <%= link_to "Connect Dropbox", DropboxApi.authorization_url, class: "button" %>
    <% end %>
  </section>

  <section class="zoom">
    <h2>Zoom</h2>
    <% if @zoom_connected %>
      <p>You are connected to Zoom as
        <strong><%= current_user.zoom_email || "Unknown User" %></strong></p>
      <form method="post" action="<%= zoom_disconnect_path %>">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <button type="submit" class="button button-dismiss disconnect">Disconnect Zoom</button>
      </form>
    <% else %>
      <p><%= link_to "Connect Zoom", zoom_connect_path, class: "button" %></p>
    <% end %>

    <% if @zoom_connected %>
      <% if @zoom_recordings.any? %>
        <section class="zoom">
          <h2>Recorded Meetings</h2>

          <form method="get">
            <div class="form-field">
              <label>From:</label>
              <input
                type="date"
                name="from"
                id="from_date"
                value="<%= params[:from].presence || (Time.now.utc - 1.year).strftime('%Y-%m-%d') %>"
              >
            </div>

            <div class="form-field">
              <label>To:</label>
              <input
                type="date"
                name="to"
                id="to_date"
                value="<%= params[:to].presence || Time.now.utc.strftime('%Y-%m-%d') %>"
              >
            </div>

            <div class="form-field actions">
              <button type="submit" class="button">Fetch Recordings</button>
              <%= link_to "🔄", users_path, class: "refresh" %>
            </div>
          </form>
          <div class="table-container">
            <table>
              <thead>
                <tr>
                  <th>Start Time</th>
                  <th>Meeting Name</th>
                  <th>Link</th>
                </tr>
              </thead>
              <tbody>
                <% @zoom_recordings.each do |recording| %>
                  <tr>
                    <td><%= Time.parse(recording[:start_time]).strftime("%Y-%m-%d %l:%M %P") %></td>
                    <td><%= recording[:name] %></td>
                    <td>
                      <a href="<%= recording[:recording_url] %>" target="_blank">View Recording</a>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </section>
      <% else %>
        <p>No Zoom recordings found.</p>
      <% end %>
    <% end %>
  </section>

  <section class="calendly">
    <h2>Calendly</h2>

    <% if @calendly_connected %>
      <p>You are connected to Calendly as
        <strong><%= current_user.calendly_user_email || "Unknown User" %></strong></p>
      <form method="post" action="<%= calendly_disconnect_path %>">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <button type="submit" class="button button-dismiss disconnect">Disconnect Calendly</button>
      </form>
    <% else %>
      <p><%= link_to "Connect Calendly", auth_calendly_path, class: "button" %></p>
    <% end %>

    <% if @calendly_connected && @meetings.any? %>
      <section class="calendly">
        <h2>Upcoming Meetings</h2>

        <div class="table-container">
          <table>
            <thead>
              <tr>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Meeting Name</th>
                <th>Participants</th>
              </tr>
            </thead>
            <tbody>
              <% @meetings.each do |meeting| %>
                <tr>
                  <td><%= meeting[:start_time] %></td>
                  <td><%= meeting[:end_time] %></td>
                  <td><%= meeting[:name] %></td>
                  <td>
                    <% if meeting[:participants].present? %>
                      <ul>
                        <% meeting[:participants].each do |email| %>
                          <li><a href="mailto:<%= email %>" target="_blank" rel="noopener"><%= email %></a></li>
                        <% end %>
                      </ul>
                    <% else %>
                      No participants listed
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </section>
    <% end %>
  </section>
</main>